stages:
  - validate
  - plan
  - apply

variables:
  TF_ROOT: "terraform"

before_script:
  - apk add --no-cache curl unzip bash git
  - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
  - unzip terraform.zip && mv terraform /usr/local/bin/
  - terraform -version
  - cd $TF_ROOT
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - terraform/tfplan

apply:
  stage: apply
  when: manual
  script:
    - terraform apply -auto-approve tfplan
